FORMAT: 1A
HOST: http://192.168.0.123:3000/api/v1

# iWine - умный графин для вина

### Введение
iWine API поможет тебе управлять твоим умным графином, используя http запросы через wifi.

### Как начать пользоваться?
Скачайте на мобильное устройство приложение **Smart iWine** с AppStore или PlayMarket. Если приложение уже установлено, обновите до последней версии.

Запустите приложение Smart iWine, и нажмите кнопку **&laquo;добавить устройство&raquo;**. На устройстве зажмите кнопку включения на 5 секунд, когда индикатор начнет мигать, устройство отобразиться в мобильном приложении. 

![Добавить новое устройство и присоединить к WIFI](screen.png)

### Подключение устройства к wifi
В мобильном приложении, выберите добавленное ранее устройство. Нажмите кнопку **&laquo;Присоединить к wifi&raquo;**. Введите пароль и нажмите кнопку **&laquo;Соединить&raquo;**. После успешного подключения, вы увидите IP адрес устройства в сети wifi.

*Для отправки http запросов на устройство, используйте его IP-адрес и порт - 3000, например **192.168.0.123:3000***

![Схема подключения устройств](scheme.png)

### Какие команды и данные доступны на сервере?
С помощью сервера, можно получить следующие данные:
- объем;
- содержание алкоголя;
- содержание сахара;
- температуру;
- тип вина — красное, белое, розовое, оранжевое (эта информация определяется с использованием алгоритмов машинного обучения и сопровождается некоторым коэффициентом достоверности).

Так же можно отправить на сервер команды:
- охладить или нагреть вино до определенной температуры;
- взболтать вино для насыщения его воздухом.

Ознакомитесь с доступными конечными точками на сервере ниже.

### Токен авторизации

Цифровой токен авторизации вы можете найти на обратной стороне ножки графина, 
на наклейке в коробке, а так же в приложении Smart iWine после добавления устройства.

Ключ состоит из 6 цифр. Каждый запрос должен содержать заголовок Token с данным значением.

# Group Получение данных

## Статус устройства [/]
Возвращает код состояния и текстовое сообщение о статусе устройства.

### Статус устройства  [GET]

+ Request
    + Headers
            Token: 123456

+ Response 102 (text/plain)

+ Response 200 (text/plain)

        Устройство готово к работе

+ Response 522 (text/plain)

        Тайм-аут соединения


## Объем [/capacity]
Ответ будет содержать число от 0 до 250 мл (максимальная вместимость графина). В случае ошибки возвращается 0.

### Объем жидкости [GET]

+ Request
    + Headers
            Token: 123456

+ Response 200 (text/plain)

        100


## Содержание алкоголя [/alcohol]
Ответ будет содержать число от 0 до 100. Данное число показывает уровень алкоголя в жидкости
 в процентном содержании. 

### Содержание алкоголя [GET]

+ Request
    + Headers
            Token: 123456

+ Response 200 (text/plain)

        20


## Содержание сахара [/sugar]
Ответ будет содержать число от 0 до 100. Данное число показывает количество грамм сахара
 на литр жидкости. 

### Содержание сахара [GET]

+ Request
    + Headers
            Token: 123456

+ Response 200 (text/plain)

        10


## Температура [/temperature]
Ответ будет содержать число от -10 до 50. Данное число показывает температуру жидкости в градусах Цельсия. 

### Температура [GET]

+ Request
    + Headers
            Token: 123456

+ Response 200 (text/plain)

        20


## Тип вина [/type]
Возвращает одно из четырех строковых значений: 
- white
- red
- sparkling
- rose
 
В случае отсутствия жидкости в графине или жидкости не относящейся к видам вина, возвращается значение **unknown**

### Тип вина [GET]

+ Request
    + Headers
            Token: 123456

+ Response 200 (text/plain)

        red
        

# Group Выполнение операций

## Изменение температуры [/temperature/{value}]
Данная команда может охладить или нагреть вино до определенной температуры. 

Команда выполняется асинхронно, пока не достигнет определенной температуры. 

Во время выполнения операции *индикатор на устройстве светиться красным цветом*, 
повторые запросы в этот момент недоступны и возвращают код 102.

Следить за текущей температурой можно с помощью GET запроса /temperature.

Информацию о состоянии устройства можно получить GET запросом на корневой адрес.

### Изменение температуры [POST]

+ Parameters
    + value: (number, required) - Необходимая температура в градусах Цельсия. 
Может принимать значения от -10 до 50. 


+ Request
    + Headers
            Token: 123456

+ Response 200 (text/plain)

        Операция принята к исполнению

+ Response 102 (text/plain)

        Операция уже выполняется. Дождитесь окончания операции и повторите попытку.


## Взболтать вино для насыщения воздухом [/shake/{seconds}]
Данная команда запускает механизм вращения подвижной части устройства, на время указанное в запросе.

Команда выполняется асинхронно, пока не окончится заданное время в секундах.

Во время выполнения операции *индикатор на устройстве светиться красным цветом*, 
повторые запросы в этот момент недоступны и возвращают код 102.

Информацию о состоянии устройства можно получить GET запросом на корневой адрес.

### Взболтать вино [POST]

+ Parameters
    + seconds: (number, optional) - Продолжительность вращения подвижной части графина в секундах. 
    Принимаемые значения от 1 до 600 секунд.
        + Default: `10`


+ Request
    + Headers
            Token: 123456

+ Response 200 (text/plain)

        Операция принята к исполнению

+ Response 102 (text/plain)

        Операция уже выполняется. Дождитесь окончания операции и повторите попытку.



## Отменить изменение температуры [/temperature]
Данная команда отменяет операцию изменения температуры.

### Отменить изменение температуры [DELETE]

+ Request
    + Headers
            Token: 123456

+ Response 200 (text/plain)

        Операция отменена

+ Response 404 (text/plain)

        Устройство не выполняет операцию изменения температуры


## Отменить операцию взбалтывания [/shake]
Данная команда отменяет операцию взбалтывания

### Отменить взбалтывание [DELETE]

+ Request
    + Headers
            Token: 123456

+ Response 200 (text/plain)

        Операция отменена

+ Response 404 (text/plain)

        Устройство не выполняет операцию взбалтывания
